### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Anisha7** [danield309/Captain-Rainbows-Checklist#1]
-  Allow your select() function to make a call to update() and destroy() to fulfill the requirement of using all CRUD functions.
-  Try adding a helper function that can mark an item as completed. Think of a symbol that could make it look checked/marked.

**Comment by danield309** [comment]
Fixed issues.

**Comment by Anisha7** [comment]
- Your read function does not print anything in the terminal.
- Selecting 'D' function doesn't seem to actually delete anything in your list because you aren't calling your delete function! Fix this.
- You are still missing your mark_completed() function. Did you push your code?
